[project]
name = "gnc-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "imageio>=2.37.4",
    "imageio-ffmpeg>=0.6.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "numpy-quaternion>=2024.0.13",
    "pyvista>=0.49.0",
    "scipy>=1.18.1",
    "tqdm>=4.70.1",
]
